local _, ns = ...

-- Icon overrides used by EventQ.
-- Prefer locale-safe overrides by Holidays.db2 ID (aka C_Calendar holiday IDs), so all clients get the same icons.

ns.IconOverrides = ns.IconOverrides or {}

-- Local texture root for bundled calendar icons.
local CAL = "Interface/AddOns/EventQ/Media/Calendar/"

-- Locale-safe: Holiday/Event ID -> icon override.
-- Keys should be Holidays.db2 ID values.
ns.IconOverrides.byId = {
  [141] = { icon = CAL .. "calendar_winterveilstart.tga", texCoord = { 0, 1, 0, 1 } },
  [181] = { icon = CAL .. "calendar_noblegardenstart.tga", texCoord = { 0, 1, 0, 1 } },
  [201] = { icon = CAL .. "calendar_childrensweekstart.tga", texCoord = { 0, 1, 0, 1 } },
  [321] = { icon = CAL .. "calendar_harvestfestivalstart.tga", texCoord = { 0, 1, 0, 1 } },
  [324] = { icon = CAL .. "calendar_hallowsendstart.tga", texCoord = { 0, 1, 0, 1 } },
  [327] = { icon = CAL .. "calendar_lunarfestivalstart.tga", texCoord = { 0, 1, 0, 1 } },
  [335] = { icon = CAL .. "calendar_loveintheairstart.tga", texCoord = { 0, 1, 0, 1 } },
  [341] = { icon = CAL .. "calendar_midsummerstart.tga", texCoord = { 0, 1, 0, 1 } },
  [372] = { icon = CAL .. "calendar_brewfeststart.tga", texCoord = { 0, 1, 0, 1 } },
  [398] = { icon = CAL .. "calendar_piratesday.tga", texCoord = { 0, 1, 0, 1 } },
  [404] = { icon = CAL .. "calendar_harvestfestivalstart.tga", texCoord = { 0, 1, 0, 1 } },
  [409] = { icon = CAL .. "calendar_dayofthedeadstart.tga", texCoord = { 0, 1, 0, 1 } },
  [423] = { icon = CAL .. "calendar_loveintheairstart.tga", texCoord = { 0, 1, 0, 1 } },
  [479] = { icon = CAL .. "calendar_darkmoonfaireelwynnstart.tga", texCoord = { 0, 1, 0, 1 } },
  [559] = { icon = CAL .. "calendar_weekendburningcrusadestart.tga", texCoord = { 0, 1, 0, 1 } },
  [561] = { icon = CAL .. "calendar_weekendpvpskirmishstart.tga", texCoord = { 0, 1, 0, 1 } },
  [562] = { icon = CAL .. "calendar_weekendwrathofthelichkingstart.tga", texCoord = { 0, 1, 0, 1 } },
  [563] = { icon = CAL .. "calendar_weekendbattlegroundsstart.tga", texCoord = { 0, 1, 0, 1 } },
  [565] = { icon = CAL .. "calendar_weekendpetbattlesstart.tga", texCoord = { 0, 1, 0, 1 } },
  [587] = { icon = CAL .. "calendar_weekendcataclysmstart.tga", texCoord = { 0, 1, 0, 1 } },
  [592] = { icon = CAL .. "achievement_reputation_08.tga", texCoord = { 0, 1, 0, 1 } },
  [599] = { icon = CAL .. "calendar_weekendpetbattlesstart.tga", texCoord = { 0, 1, 0, 1 } },
  [600] = { icon = CAL .. "calendar_weekendpetbattlesstart.tga", texCoord = { 0, 1, 0, 1 } },
  [601] = { icon = CAL .. "calendar_weekendpetbattlesstart.tga", texCoord = { 0, 1, 0, 1 } },
  [602] = { icon = CAL .. "calendar_weekendbattlegroundsstart.tga", texCoord = { 0, 1, 0, 1 } },
  [603] = { icon = CAL .. "calendar_weekendbattlegroundsstart.tga", texCoord = { 0, 1, 0, 1 } },
  [604] = { icon = CAL .. "calendar_weekendbattlegroundsstart.tga", texCoord = { 0, 1, 0, 1 } },
  [610] = { icon = CAL .. "calendar_weekendpvpskirmishstart.tga", texCoord = { 0, 1, 0, 1 } },
  [611] = { icon = CAL .. "calendar_weekendpvpskirmishstart.tga", texCoord = { 0, 1, 0, 1 } },
  [612] = { icon = CAL .. "calendar_weekendpvpskirmishstart.tga", texCoord = { 0, 1, 0, 1 } },
  [613] = { icon = CAL .. "achievement_reputation_08.tga", texCoord = { 0, 1, 0, 1 } },
  [614] = { icon = CAL .. "achievement_reputation_08.tga", texCoord = { 0, 1, 0, 1 } },
  [615] = { icon = CAL .. "achievement_reputation_08.tga", texCoord = { 0, 1, 0, 1 } },
  [616] = { icon = CAL .. "calendar_weekendburningcrusadestart.tga", texCoord = { 0, 1, 0, 1 } },
  [617] = { icon = CAL .. "calendar_weekendburningcrusadestart.tga", texCoord = { 0, 1, 0, 1 } },
  [618] = { icon = CAL .. "calendar_weekendburningcrusadestart.tga", texCoord = { 0, 1, 0, 1 } },
  [622] = { icon = CAL .. "calendar_weekendwrathofthelichkingstart.tga", texCoord = { 0, 1, 0, 1 } },
  [623] = { icon = CAL .. "calendar_weekendwrathofthelichkingstart.tga", texCoord = { 0, 1, 0, 1 } },
  [624] = { icon = CAL .. "calendar_weekendwrathofthelichkingstart.tga", texCoord = { 0, 1, 0, 1 } },
  [628] = { icon = CAL .. "calendar_weekendcataclysmstart.tga", texCoord = { 0, 1, 0, 1 } },
  [629] = { icon = CAL .. "calendar_weekendcataclysmstart.tga", texCoord = { 0, 1, 0, 1 } },
  [630] = { icon = CAL .. "calendar_weekendcataclysmstart.tga", texCoord = { 0, 1, 0, 1 } },
  [634] = { icon = CAL .. "calendar_hatchingofthehippogryphs.tga", texCoord = { 0, 1, 0, 1 } },
  [635] = { icon = CAL .. "calendar_volunteerguardday.tga", texCoord = { 0, 1, 0, 1 } },
  [638] = { icon = CAL .. "calendar_callofthescarabstart.tga", texCoord = { 0, 1, 0, 1 } },
  [642] = { icon = CAL .. "calendar_thousandboatbashstart.tga", texCoord = { 0, 1, 0, 1 } },
  [643] = { icon = CAL .. "calendar_weekendmistsofpandariastart.tga", texCoord = { 0, 1, 0, 1 } },
  [644] = { icon = CAL .. "calendar_ungoromadnessstart.tga", texCoord = { 0, 1, 0, 1 } },
  [645] = { icon = CAL .. "calendar_springballoonfestivalstart.tga", texCoord = { 0, 1, 0, 1 } },
  [646] = { icon = CAL .. "calendar_taverncrawl.tga", texCoord = { 0, 1, 0, 1 } },
  [647] = { icon = CAL .. "calendar_marchofthetadpoles.tga", texCoord = { 0, 1, 0, 1 } },
  [648] = { icon = CAL .. "calendar_glowcapfestival.tga", texCoord = { 0, 1, 0, 1 } },
  [652] = { icon = CAL .. "calendar_weekendmistsofpandariastart.tga", texCoord = { 0, 1, 0, 1 } },
  [654] = { icon = CAL .. "calendar_weekendmistsofpandariastart.tga", texCoord = { 0, 1, 0, 1 } },
  [656] = { icon = CAL .. "calendar_weekendmistsofpandariastart.tga", texCoord = { 0, 1, 0, 1 } },
  [658] = { icon = CAL .. "inv_misc_missilelarge_red.tga", texCoord = { 0, 1, 0, 1 } },
  [659] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [660] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [662] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [663] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [664] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [666] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [667] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [669] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [670] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [671] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [673] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [674] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [676] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [677] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [678] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [680] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [681] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [683] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [684] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [685] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [687] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [688] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [691] = { icon = CAL .. "calendar_transmogpopularityconteststart.tga", texCoord = { 0, 1, 0, 1 } },
  [692] = { icon = CAL .. "calendar_danceday.tga", texCoord = { 0, 1, 0, 1 } },
  [694] = { icon = CAL .. "calendar_moonkinfestival.tga", texCoord = { 0, 1, 0, 1 } },
  [696] = { icon = CAL .. "calendar_runningofthegnomesstart.tga", texCoord = { 0, 1, 0, 1 } },
  [701] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [702] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [704] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [705] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [706] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [736] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [737] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1047] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1048] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1049] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1050] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1051] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1052] = { icon = CAL .. "calendar_wanderersfestival.tga", texCoord = { 0, 1, 0, 1 } },
  [1053] = { icon = CAL .. "calendar_freetshirtday.tga", texCoord = { 0, 1, 0, 1 } },
  [1054] = { icon = CAL .. "calendar_vashjirdivingday.tga", texCoord = { 0, 1, 0, 1 } },
  [1056] = { icon = CAL .. "calendar_weekendwarlordsofdraenorstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1062] = { icon = CAL .. "calendar_vashjirdivingday.tga", texCoord = { 0, 1, 0, 1 } },
  [1063] = { icon = CAL .. "calendar_weekendwarlordsofdraenorstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1065] = { icon = CAL .. "calendar_weekendwarlordsofdraenorstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1068] = { icon = CAL .. "calendar_weekendwarlordsofdraenorstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1120] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1121] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1122] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1123] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1124] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1166] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1167] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1168] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1169] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1170] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1221] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1232] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1233] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1234] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1235] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1236] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1237] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1238] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1239] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1240] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1241] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1242] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1243] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1244] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1245] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1246] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1263] = { icon = CAL .. "calendar_weekendlegionstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1265] = { icon = CAL .. "calendar_weekendlegionstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1267] = { icon = CAL .. "calendar_weekendlegionstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1269] = { icon = CAL .. "calendar_weekendlegionstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1307] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1308] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1309] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1310] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1311] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1312] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1382] = { icon = CAL .. "calendar_greedyemissarystart.tga", texCoord = { 0, 1, 0, 1 } },
  [1395] = { icon = CAL .. "calendar_kalimdorcupstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1400] = { icon = CAL .. "calendar_easternkingdomscupstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1405] = { icon = CAL .. "calendar_hallowsendstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1407] = { icon = CAL .. "calendar_outlandcupstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1408] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1425] = { icon = CAL .. "calendar_turbulenttimewaysstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1429] = { icon = CAL .. "calendar_northrendcupstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1452] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1453] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1454] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1455] = { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } },
  [1458] = { icon = CAL .. "calendar_turbulenttimewaysstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1459] = { icon = CAL .. "calendar_turbulenttimewaysstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1460] = { icon = CAL .. "calendar_turbulenttimewaysstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1508] = { icon = CAL .. "calendar_weekendclassicstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1558] = { icon = CAL .. "calendar_weekendthewarwithinstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1559] = { icon = CAL .. "calendar_delvesstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1560] = { icon = CAL .. "calendar_delvesstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1561] = { icon = CAL .. "calendar_delvesstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1562] = { icon = CAL .. "calendar_delvesstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1563] = { icon = CAL .. "calendar_weekendthewarwithinstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1564] = { icon = CAL .. "calendar_weekendthewarwithinstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1565] = { icon = CAL .. "calendar_weekendthewarwithinstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1583] = { icon = CAL .. "calendar_weekendclassicstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1584] = { icon = CAL .. "calendar_weekendclassicstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1585] = { icon = CAL .. "calendar_weekendclassicstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1601] = { icon = CAL .. "calendar_plunderstormstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1633] = { icon = CAL .. "calendar_plunderstormstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1634] = { icon = CAL .. "calendar_plunderstormstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1635] = { icon = CAL .. "calendar_plunderstormstart.tga", texCoord = { 0, 1, 0, 1 } },
  -- Dragonflight launch celebration.
  [1636] = { icon = CAL .. "calendar_dragonflightstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1640] = { icon = CAL .. "calendar_timerunningstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1641] = { icon = CAL .. "calendar_timerunningstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1642] = { icon = CAL .. "calendar_timerunningstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1643] = { icon = CAL .. "calendar_timerunningstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1644] = { icon = CAL .. "calendar_timerunningstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1666] = { icon = CAL .. "calendar_weekendbattleforazerothstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1667] = { icon = CAL .. "calendar_weekendbattleforazerothstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1668] = { icon = CAL .. "calendar_weekendbattleforazerothstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1669] = { icon = CAL .. "calendar_weekendbattleforazerothstart.tga", texCoord = { 0, 1, 0, 1 } },
  -- Dragonflight pre-patch / launch-related weekend variants.
  [1670] = { icon = CAL .. "calendar_dragonflightstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1671] = { icon = CAL .. "calendar_dragonflightstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1672] = { icon = CAL .. "calendar_dragonflightstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1674] = { icon = CAL .. "calendar_weekendapexisstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1683] = { icon = CAL .. "calendar_dragonflightstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1688] = { icon = CAL .. "calendar_greedyemissarystart.tga", texCoord = { 0, 1, 0, 1 } },
  [1691] = { icon = CAL .. "calendar_greedyemissarystart.tga", texCoord = { 0, 1, 0, 1 } },
  [1692] = { icon = CAL .. "calendar_greedyemissarystart.tga", texCoord = { 0, 1, 0, 1 } },
  [1693] = { icon = CAL .. "calendar_greedyemissarystart.tga", texCoord = { 0, 1, 0, 1 } },
  [1694] = { icon = CAL .. "calendar_weekendapexisstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1695] = { icon = CAL .. "calendar_weekendapexisstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1696] = { icon = CAL .. "calendar_weekendapexisstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1697] = { icon = CAL .. "calendar_timerunningstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1703] = { icon = CAL .. "calendar_weekendshadowlandsstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1705] = { icon = CAL .. "calendar_weekendshadowlandsstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1707] = { icon = CAL .. "calendar_weekendshadowlandsstart.tga", texCoord = { 0, 1, 0, 1 } },
  [1709] = { icon = CAL .. "calendar_weekendshadowlandsstart.tga", texCoord = { 0, 1, 0, 1 } },
}

-- Locale-dependent fallbacks (used only when a stable holidayID isn't available).
-- Keep this list minimal to avoid surprises on non-English clients.
ns.IconOverrides.byTitleContains = {
  { "PvP Brawl", { icon = CAL .. "calendar_brawl.tga", texCoord = { 0, 1, 0, 1 } } },
}
